### ISSUE TITLE
use standard `kubernetes.io/tls` secret

### ISSUE THREAD

**Issue by delgod** [redhat-cop/cert-operator#27]
Hi!

I am testing 0.2.0 version and as I can see operator produce just regular secret.
Kubernetes has a standard secret type for TLS, I believe the operator should produce `kubernetes.io/tls` secrets.

how to create TLS secret manually:
```
kubectl create secret tls cluster3-certificate --cert=./server-cert.pem --key=./server-key.pem
````

**Comment by etsauer** [comment]
@delgod yes, good callout. Totally agree.

**Comment by etsauer** [comment]
@delgod can we go ahead and close this issue now that the PR is merged?

**Comment by delgod** [comment]
yes, thank you!
