### ISSUE TITLE
deploy/deployment.yaml is missing

### ISSUE THREAD

**Issue by utle** [redhat-cop/cert-operator#58]
In the README has the following step:
oc apply -f deploy/deployment.yaml

However, there is no deployment.yaml file. Maybe, this step should be oc apply -f deploy/operator.yaml? 

The deployment.yaml deleted by issue#26 so the README need to update.

**Comment by Zech-Hein** [comment]
Additionally, when trying to deploy the following error occurs,
```  
Failed to pull image "docker-registry.default.svc:5000/default/cert-operator:latest": rpc error: code = Unknown desc = Error: image default/cert-operator:latest not found
```  
It seems like the image is not there

**Comment by utle** [comment]
The image is not there because the repository doesn't exist.
(3) failed to list versions for git://github.com/micro/go-config: fatal: remote error: 
  Repository not found.

**Comment by JuozasA** [comment]
Re: file name: #https://github.com/redhat-cop/cert-operator/pull/59

**Comment by JuozasA** [comment]
> Additionally, when trying to deploy the following error occurs,
> 
> ```
> Failed to pull image "docker-registry.default.svc:5000/default/cert-operator:latest": rpc error: code = Unknown desc = Error: image default/cert-operator:latest not found
> ```
> 
> It seems like the image is not there

make sure you build the image and push it to your local registry first:
oc process -f build/build.yml | oc apply -f-
